### ISSUE TITLE
Add utility functions

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#120]
A common set of utility functions are needed to perform some common tasks and to have higher level of code reuse and modularity. It has not been decided yet what exact functions will be included, but at least the following needs are addressed:
- File I/O
- NoData handling
- Common operations on dataframes and rasters
- Checks (converting checks as a submodule of utilities will be considered)

**Comment by nialov** [comment]
While implementing the `rasterize` functionality, I noticed that it allows the
input of a base raster to use as the "canvas" in which to burn the rasterized
vectors in. However, only the profile of the raster is needed, not the full
`DatasetReader`. I have noticed that the full `DatasetReader` is often passed
around in `eis_toolkit` even though only the profile of the raster would be
sufficient. I propose an utility function to get the profile of a raster:

~~~python
from pathlib import Path

import rasterio
from rasterio import profiles


def raster_profile(raster_path: Path)->profiles.Profile:
    with rasterio.open(raster_path) as raster:
        profile = raster.profile
    return profile
~~~

It is simple, but it is useful to avoid having to use a context manager or
passing around the full `DatasetReader`.
    
Example `profiles.Profile` contents:

~~~
{'count': 1,
 'crs': CRS.from_epsg(3067),
 'driver': 'GTiff',
 'dtype': 'float64',
 'height': 8,
 'interleave': 'band',
 'nodata': -999.999,
 'tiled': False,
 'transform': Affine(2.0, 0.0, 384760.5,
       0.0, -2.0, 6671362.5),
 'width': 10}
~~~

**Comment by nialov** [comment]
> Yes, I think we could have this as one of the utility functions. Would a similar function be useful for raster.meta, or is there any reason even to use meta instead of profile (as I understand, profile has the same information and some additional information)?

I believe profile has the most comprehensive metadata. So it should contain all `meta` attributes as well.
