### ISSUE TITLE
Add MLP (multilayer perceptron)

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#129]

**Comment by zelioluca** [comment]
ok I do this!

**Comment by nmaarnio** [comment]
Where did you push MLP code? I just assigned you here so since I thought you finalize some MLP (and CNN) code and thought we could link the MLP branch and PR to this issue so this gets closed automatically.

**Comment by zelioluca** [comment]
Let me check

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zelioluca** [comment]
One is here! He says probability there, we can just change a variable to switch between probability and class based

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by zelioluca** [comment]
Hi Niko I placed the add_MLP_probability PR I think that this branch is
older then the master a lot of exception s and file were missing! If it is
no good We can close this branch and open new one! Let me know
