### ISSUE TITLE
Add reclassify raster

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#141]

**Comment by lehtonenp** [comment]
I have noticed now on several reclassifying occasions that Mapclassify provide many of the reclassification functions. However, manual breaks, equal intervals and quantiles are faster to create with Numpy. Manual breaks and quantiles provide the same results with n = 1 000 000 randomized lists. Equal interval gives differing answers on the first ~100 cells in a 10k x 10k matrix.

**Comment by lehtonenp** [comment]
There is an algorithm made by Torppa for geometrical intervals. I believe geometrical intervals are not found as is in any library. Hence it should at least be implemented as with our custom logic.

**Comment by lehtonenp** [comment]
Manual breaks is also implemented in Mapclassify. Numpy and Mapclassify provides the same result but Numpy is much faster.

**Comment by lehtonenp** [comment]
For defined intervals Mapclassify and Numpy have the exact same result. Numpy is also in this case much faster with MCF_DEM_EIS.tif.

**Comment by lehtonenp** [comment]
For equal interval the following results are made by Numpy and Mapclassify

Numpy:

  Interval     Count
--------------------
[2.503, 3.039] |   515 
(3.039, 4.724 ] |   513 
(4.724 , 5.621 ] |   514 
(5.621 , 6.444 ] |   518 
(6.444, 9.67] |   516

Mapclassify:

  Interval     Count
--------------------
[2.50, 3.94] |   840
(3.94, 5.37] |   529
(5.37, 6.80] |   741
(6.80, 8.24] |   112
(8.24, 9.67] |   354

**Comment by lehtonenp** [comment]
With MCF_DEM_EIS.tif file manual breaks differ by only one cell between Numpy and Mapclassify. The time difference is ~76 seconds. Numpy classifies the data in 1.7 seconds and Mapclassify in 77 seconds.

**Comment by nmaarnio** [comment]
Closing, feature implemented
