### ISSUE TITLE
Optimize IDW

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#208]
The current implementation of IDW does not work well on large datasets as it allocates large amounts of memory for temporary arrays.

**Comment by tomiturunen1** [comment]
I tried to implement the IDW calculations using scipy and pykrige, but it didn't seem any faster and it doesn't resolve the out of memory problem.

**Comment by RaineEkman** [comment]
The current matrix manipulation in `_idw_core`  looks pretty elegant, but first it gets as arguments two arrays that contain a lot of redundancy (`xi`, `yi`, both the same size as the desired output, only containing one row or column worth of real information) and then creates 3 more arrays (`d0`,`d1`,`dist`) sized like the output multiplied by the number of interpolation points. So, taking into account the `weights `and `interpolated_values `arrays, for an output of N elements and P points it adds up to _N*(3P+4)._
https://github.com/GispoCoding/eis_toolkit/blob/7094ef33bf2d163f8e68ad5524684c65a4f1f8ba/eis_toolkit/vector_processing/idw_interpolation.py#L65

I think a loop over the points could get the memory requirement down to roughly _4N_.
