### ISSUE TITLE
Add winsorizing function

### ISSUE THREAD

**Issue by pavetsu14** [GispoCoding/eis_toolkit#22]
Create a new branch (from master branch) and add
- [ ] winsorize.py file into eis_toolkit/eis_toolkit/transformations folder (corresponds to clip.py)
- [ ] winsorize_test.py file into eis_toolkit/tests folder (corresponds to clip_test.py). Utilize data in Teams folder in your tests if possible (if not possible, add necessary files to the Teams folder)!
- [ ] more custom exception classes for eis_toolkit/eis_toolkit/exceptions.py

Optional additions:
- [ ] a new jupyter lab notebook file into eis_toolkit/notebooks folder for testing winsorize tool in practice (corresponds to testing_clip.ipynb)
- [ ] a new page into documentation site (see instructions folder and documentation.md for help)

Do not make too large commits. Rather multiple commits than one massive commit :) After finishing the branch, create a pull request and add @pavetsu14 or @eemilhaa as Reviewer.

**Comment by nmaarnio** [comment]
Closing this as development is now part of issue #98
