### ISSUE TITLE
Weights of evidence: Failure of weights generalization

### ISSUE THREAD

**Issue by chudasama-bijal** [GispoCoding/eis_toolkit#227]
Add a functionality to handle failure of weights generalization in the weights of evidence method.

There will be instances when generalization of classes for the given studentized contrast threshold will fail for the 'weights_of_evidence_calculate_weights' function. In such cases an informative error could be displayed, and the weights calculations results could be provided to the user, so that the user can evaluate the weights and run the weights calculations again with a suitable threshold.

Alternatively, the users could also be provided with an option of user-defined generalization of classes.

**Comment by RichardScottOZ** [comment]
Sounds like a good idea.
