### ISSUE TITLE
check_minmax_position() not returning bool

### ISSUE THREAD

**Issue by AlVella** [GispoCoding/eis_toolkit#229]
check_minmax_position() in checks.parameter module returns a np.bool_ type object instead of a bool, returning a BeartypeCallHintReturnViolation error (expecting bool as output, getting np.bool_ instead).

Seen this bug occurring when using create_constant_raster() function.

Replacing :

`return parameter[0] < parameter[1]`

With :

`return bool(parameter[0] < parameter[1])`

in check_minmax_position() function seems to solve this problem.

**Comment by msorvoja** [comment]
@AlVella I can't seem to reproduce this error. Please provide me with the parameters used when facing it.

**Comment by AlVella** [comment]
I tried the following code:

```
mask_poly = geopandas.read_file(r"C:\Users\vella\Desktop\EIS_Toolkit\BRGM_GranPeg_Armorican_Massif\Geology\Mask_Brittany.shp")

west = mask_poly.total_bounds[0]
east = mask_poly.total_bounds[2]
south = mask_poly.total_bounds[1]
north = mask_poly.total_bounds[3]

out_array, out_meta = create_constant_raster.create_constant_raster(0,
    coord_west = west,
    coord_north = north,
    coord_east = east,
    coord_south = south,
    target_epsg = mask_poly.crs.to_epsg(),
    target_pixel_size = 1000,
    raster_width = 372,
    raster_height = 312,
    nodata_value = -999)
```

And got the follwing error:

`BeartypeCallHintReturnViolation: @beartyped eis_toolkit.utilities.checks.parameter.check_minmax_position() return "True" violates type hint <class 'bool'>, as <protocol "numpy.bool_"> "True" not instance of bool.`
