### ISSUE TITLE
Change pca.py to use geospatial rasters instead of dataframes.

### ISSUE THREAD

**Issue by iiroseppa** [GispoCoding/eis_toolkit#233]
Dataframes are not a good way to represent a geospatial raster, because spatial and nodatavalue metadata of the raster is thrown out, and depending on the situation it is unnecessarily complicated or impossible to reconstruct output that is also a geospatial raster with same spatial dimensions as the input.

Nodata handling should also be added to the function. Nodata values are completely normal part of any geospatial raster, since they mark the shape and boundaries of the valid data, which is often not straight and rectangular. Thus they are extremely common and should always be assumed to be present.

Since a result is given for every (valid) input pixel, the output should definitely be a geospatial raster also. This is how basically every gis software works with rasters, and the user excepts to get a geospatial raster back. Conversion of original geospatial raster data to dataframe is only ok to do when the output is not given for each pixel, i.e. the output is a plot or descriptive statistics.

**Comment by nmaarnio** [comment]
Hey,

The current version of PCA accepts Numpy arrays, dataframes, geodataframes and rasters. The output format is same as input format, so if user wishes to use rasters as input, they will get a raster output. I thought it is good to offer a flexible interface, even if rasters are the "best" or most common way to conduct PCA for geospatial data. However, I wonder if you might have an old version of the PCA function / EIS Toolkit, or did you mean that we should remove all other options than to use raster?

Regarding nodata, there is some nodata handling included, but it could be that it is insufficient. If this is the case, could you suggest a modification to nodata handling here?

**Comment by iiroseppa** [comment]
Hi, it seems that I had a old version. Since PCA can be used also for vector processing, maybe those options should just be left as is.
