### ISSUE TITLE
Change k_means_cluster.py to use geospatial rasters instead of dataframes

### ISSUE THREAD

**Issue by iiroseppa** [GispoCoding/eis_toolkit#235]
Dataframes are not a good way to represent a geospatial raster, because spatial and nodatavalue metadata of the raster is thrown out, and depending on the situation it is unnecessarily complicated or impossible to reconstruct output that is also a geospatial raster with same spatial dimensions as the input.

Nodata handling should also be added to the function. Nodata values are completely normal part of any geospatial raster, since they mark the shape and boundaries of the valid data, which is often not straight and rectangular. Thus they are extremely common and should always be assumed to be present.

Since a result is given for every (valid) input pixel, the output should definitely be a geospatial raster also. This is how basically every gis software works with rasters, and the user excepts to get a geospatial raster back. Conversion of original geospatial raster data to dataframe is only ok to do when the output is not given for each pixel, i.e. the output is a plot or descriptive statistics.

**Comment by nmaarnio** [comment]
K-means clustering was listed as vector processing tool initially, and it also takes vector data in QGIS. The thought that it could be used for rasters did not even cross my mind, to be honest. It sounds strange to me, but again, I'm not expert in the field. Can someone else comment this one too?

**Comment by iiroseppa** [comment]
Hi!
This explains a lot, thank you, I hadn't thought that it was planned to be vector only. And yes, K-means can be used also for rasters. A quick search revealed [this review article](https://www.mdpi.com/2072-4292/9/9/967) that mentions that it has been used for remote sensing imagery. 

Now I am thinking that the code should be modified to also accept rasters. I think it would be a relatively easy way to increase the functionality. Any thoughts?

**Comment by RichardScottOZ** [comment]
> K-means clustering was listed as vector processing tool initially, and it also takes vector data in QGIS. The thought that it could be used for rasters did not even cross my mind, to be honest. It sounds strange to me, but again, I'm not expert in the field. Can someone else comment this one too?
> 
> I have same thoughts about the DBSCAN issue #234

The above commentary is correct.

Data should be used from the source, generally.  Various ml processes use arrays natively - so this shouldn't be too surprising.  Rasters are arrays with metadata when you think about it that way.   Why add extra steps?

When things use tables [e.g. vector data] in ml work, they are handling the array conversion in the background for you.

The ability to do it with both is good though - if users want dataframes out for other reasons - say they want to dump points to a generic format that [other expensive software can read] so they can make a 3D surface out of something.

I am not sure if the aim is to make 'everything here work in QGIS' but there is no reason you can't have your own QGIS/raster processing adaptatiions as far as that end goes.

**Comment by nmaarnio** [comment]
Let's then add a new K-means clustering tool that takes in rasters. I'll start working on it.
