### ISSUE TITLE
limit the usage of raster_to_dataframe.py in the toolkit as much as possible

### ISSUE THREAD

**Issue by iiroseppa** [GispoCoding/eis_toolkit#238]
In my opinion, the usage of this tool encourages bad practice of using dataframes when the user input is a geospatial raster and output would be most useful as a geospatial raster. This is how basically every gis software works with rasters, and the user excepts to get a geospatial raster back. Conversion of original geospatial raster data to dataframe is only ok to do when the output is not given for each pixel, i.e. the output is a plot or descriptive statistics. A separate issue has been raised for all modules that I have found so far with this issue. 

Dataframes are not a good way to represent a geospatial raster, because spatial and nodatavalue metadata of the raster is thrown out, and depending on the situation it is unnecessarily complicated or impossible to reconstruct output that is also a geospatial raster with same spatial dimensions as the input.

I wish to hear comments and ideas about this.

**Comment by nmaarnio** [comment]
`raster_to_dataframe` is not used internally by any other EIS Toolkit function at the moment. Do you suggest to remove it wholly? I was not the one who listed this as one tool to implement, but as we aim to offer a comprehensive set of tools, it makes sense to me to include such a conversion tool. We could perhaps add a remark in the docstring about this, if we want to guide the user? If someone else has an opinion about this matter, it would be good to hear more comments

**Comment by nialov** [comment]
Agreed, raster data is always best processed as raster data, but as Niko said this is not a problem in the current toolkit? Are there some functions and/or pull requests where this is a problem and should be refactored?

**Comment by nmaarnio** [comment]
Closing this issue as I think the discussion is resolved for now.
