### ISSUE TITLE
Add missing functions to CLI

### ISSUE THREAD

**Issue by Mtk112** [GispoCoding/eis_toolkit#243]
Add missing functions to cli.py

Added:
- Feature importance (draft)
- Chi-square test
- Normality test
- Weights of evidence calculate weights
- Weights of evidence calculate response
- Resampling
- Unique combinations
- AUC
- Calculate base metrics
- Plot correlation matrix (draft)
- Plot prediction area curve

**Comment by nmaarnio** [comment]
Closing this as not anymore relevant (individual CLI functions linked to other issues)
