### ISSUE TITLE
Correction for Cell-Based Association _to_raster() function

### ISSUE THREAD

**Issue by AlVella** [GispoCoding/eis_toolkit#246]
Current implementation of _to_raster() export function does not work with regional datasets (e.g. Armorican Massif, Finnish IOCG): it is only able to work when the grid produced by the algorithm covers the whole inputed geological map (e.g. a 50K map sheet) . 

Optimization within the code drops cells without data, producing gaps when processing regional geological maps. The _to_raster() function is unable to create the raster due to those gaps.

I have corrected the _to_raster() function to solve this problem and improve computation time to export of the multi-band raster of the CBA. A better handling of no_data values is also added to this function. Implementation could be done quickly with a pull request.

**Comment by nmaarnio** [comment]
If you have already done these fixes / optimizations, you can go ahead and open a PR!
