### ISSUE TITLE
Add smoothing functions

### ISSUE THREAD

**Issue by msmiyels** [GispoCoding/eis_toolkit#257]
Add functionality for smoothing and denoising raster data:

- [ ] gaussian 
- [ ] dyn. lowpass; mean; median
- [ ] mexican hat
- [ ]  dynamic filter sizes
- [ ] lee/frost/kuan filters if possible, e.g. using [findpeaks](https://pypi.org/project/findpeaks/) if we can add this to the req. libraries

**Comment by nmaarnio** [comment]
@msmiyels , I couldn't tag you directly in EIS QGIS Plugin repository for some reason, but if you have a bit of time, could you take a look at the dicsussion in PR https://github.com/GispoCoding/eis_qgis_plugin/pull/94 regarding minimum values for the parameter? I am not 100% I gave correct advice there, so please go correct me if you spot an issue
