### ISSUE TITLE
Add smoothing/filter CLI functions

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#293]

**Comment by nmaarnio** [comment]
Yes, I think we could think about the derivates too. And yes, we can discuss these on Wednesday if you think it won't take too long

**Comment by msorvoja** [comment]
I made cli functions for these filter functions. When testing with the same raster data as the tests for these functions (which pass), I get `SystemError: <built-in function len> returned a result with an exception set` with Lee enhanced, frost and kuan filters.
