### ISSUE TITLE
GDAL issues in Ubuntu environments

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#328]
Poetry and Docker testing workflows are failing now because they try to use too new version of GDAL. See PR #320 for example. I assume Ubuntu users who try to install the environment will encounter the same issue now. Do you have ideas how to overcome this issue @nialov? Of course users could modify locally their `pyproject.toml` to lock a suitable GDAL for the time of installation and revert the file after that, but this wouldn't fix the GH workflows and does not sound optimal.

**Comment by nialov** [comment]
So this is related to an updated `poetry.lock`? You probably should not update packages in `poetry.lock` in just any feature branch. Instead you can run `poetry lock --no-update` to only add needed changes from e.g. `pyproject.toml` changes. Anyway, if the `poetry.lock` update is necessary, you can try removing the restrictions in the workflows for `GDAL==3.4.3`:

~~~diff
diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
index d84f933..aaed950 100644
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -25,7 +25,7 @@ jobs:
           sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable
           sudo apt-get update
           sudo apt-get install gdal-bin libgdal-dev
-          pip install GDAL==3.4.3 poetry
+          pip install poetry
           poetry install
       - name: Test with pytest
         run: |
diff --git a/Dockerfile-docs b/Dockerfile-docs
index 198f0d2..a8dfe75 100755
--- a/Dockerfile-docs
+++ b/Dockerfile-docs
@@ -1,4 +1,4 @@
-FROM ubuntu:22.04
+FROM ubuntu:latest
 
 EXPOSE 8888
 EXPOSE 8000
~~~
