### ISSUE TITLE
fuzzy sum logic

### ISSUE THREAD

**Issue by RichardScottOZ** [GispoCoding/eis_toolkit#380]
If you are looking to end up with a number between 0 and 1:

```python
 return data.sum(axis=0) - np.prod(data, axis=0)
```
This is clearly wrong.

Consider 3 rasters where the pixel value is 0.4 at a given index  = 0.4 + 0.4 + 0.4 - 04*0.4*0.4 > 1

what you actually want if you are trying to match something a la giant company version

```python
product_term =np.prod(1 - data, axis=0)
fuzzysum = 1 - product_term
```

**Comment by nmaarnio** [comment]
Yeah you are right. Thanks for noticing and pointing this out. I'll go ahead and fix this like you suggested
