### ISSUE TITLE
Add Invert data tool or modify Min-max scaling

### ISSUE THREAD

**Issue by nmaarnio** [GispoCoding/eis_toolkit#405]
Either a tool that allows to invert data values or modification to min-max scale that allows data inversion should be implemented (requested feature).

**Comment by okolekar** [comment]
Is this issue related to conversion of the 0 within the polygon to 1s and having an option for maximum distance to be considered beyond which the distance becomes zero? Eg. See the picture below.
![image](https://github.com/user-attachments/assets/2827b8dd-269b-4421-8d79-285ed4696f5a)

**Comment by nmaarnio** [comment]
Min-max allows now to invert scale data, closing
