### ISSUE TITLE
Coda Transformations - Data Closure

### ISSUE THREAD

**Issue by chudasama-bijal** [GispoCoding/eis_toolkit#448]
@em-t 
The coda transformation functions seem to assume that the data is closed to a constant sum. However, this is a pre-requisite and should not be considered optional. The checks whether the data is closed and belongs to simplex space should be run on the data before implementing the coda transformations, otherwise the results will not conform to the transformation procedures. Or do these functions implement closure in the background? It doesn't seem so.

**Comment by nmaarnio** [comment]
Closing as this is now completed
