### ISSUE TITLE
Add basic plotting functions for exploratory analysis.

### ISSUE THREAD

**Issue by sahautal** [GispoCoding/eis_toolkit#77]
Add basic plotting functions for exploratory analysis: functions to plot histograms, scatterplots, and boxplots from numpy ndarray input data.

**Comment by nmaarnio** [comment]
As commented in the corresponding PR, tthe plans for developing plotting functions have changed somewhat and a new branch and issue were created for this purpose. The new relevant issue is https://github.com/GispoCoding/eis_toolkit/issues/117.
