### ISSUE TITLE
Implement a draft command-line interface for `eis_toolkit`

### ISSUE THREAD

**Issue by nialov** [GispoCoding/eis_toolkit#96]
# Problem

If `eis_toolkit` is called using the command-line (e.g. using the `subprocess` module in Python) from the QGIS frontend, it needs a defined command-line interface.

# Solution

Python has builtin solutions for creating a command-line interface (`sys.argv`, `argparse`). However, depending on the complexity it would more robust to use a mature, batteries included command-line library, such as `click` or `typer`.

Through this interface, any functions within the library can be called, but the arguments to those functions must then be provided through the command-line.

# Implementation

Addition of a command-line interface file, typically named `cli.py` at `eis_toolkit/cli.py`. Additionally, to call the same command-line interface through the module system `python -m eis_toolkit ...`, a `eis_tookit/__main__.py` file with some boilerplate code is required.

I will create a draft `click` interface in the beginning as `click` is already a dependency of the project (used by some other dependency) so no additional dependencies are required.

**Comment by nmaarnio** [comment]
Closing this issue as it is no longer relevant. CLI functions are implemented for tools as they are added to the toolkit.
