### ISSUE TITLE
Create surface derivatives

### ISSUE THREAD

**Issue by msmiyels** [GispoCoding/eis_toolkit#99]
Create functionality for surface derivatives:

- [x] aspect
- [x] slope
- [x] different curvature sets
- [x] tests for valid results/values (e.g. cut occuring outliers if necessary)

Functionality will be based on single band raster datasets only.

**Comment by nialov** [comment]
## Handling multiple bands

Do any of the functions actually do analysis based on multiple bands or do they
all take a single band as an input, process it, then move to the next band with
no information being used between the bands? If that is the case, the functions
should be simplified to only work on a single band and the calls to use the
function with multiple bands of a raster should be done upstream. If the bands
are used together, then of course multiple bands need to be available, but this
is not the case for instance for `binarize` where single bands are
binarized individually. Handling multiple bands in each function adds much
complexity. Furthermore, each function reads all the bands of the raster into
memory simultaneously. This should be avoided unless they are actually needed
simultaneously as you may run into memory issues very fast.
        
## Handling both GeoDataFrames and raster

This is a general issue that causes much unneeded complexity. There is no
reason to handle them separately in each toolkit module. Instead, we should
decide on a either or to be used as the input in all raster processing
modules/functions. Rasters from `rasterio` is my preferred choice.
GeoDataFrames, which can be assumed to be point data on a fixed grid, can be
converted to rasters via a rasterization function.

Consequently, if this seems reasonable to others as well (@nmaarnio), I would
focus all refactoring efforts in this pull request to the functions handling
raster data or even just the `_core` functions (See below.)

## Core functionality is hidden beneath the boilerplate

The actual core functionality is currently well separated with the `_core`
function naming suffixes. However, everything else in the files seems related
to handling all bands and GeoDataFrames simultaneously. Same handling with
small differences is implemented multiple times in the different files.
Functions with `_table` and `_raster` suffixes usually do the same thing across
all Python files, all related to just handling the different input data types.

This "boilerplate" functionality, as I call it, should be separated outside
this pull request, but the code done here can simply be copied there and
should not be wasted.

If this seems reasonable to others as well (@nmaarnio), I would focus
refactoring efforts to i) separating the general utilities from this pull
request to the general utilities that are being drafted by Niko. Furthermore,
ii) I would add separate tests for all the `_core` functions to make sure they
perform as expected as they are the critical part of this pull request. They
should be tested with assertions and checks that a previously known, expected,
result is returned from the functions.

## Comments by Niko

> I am somewhat torn trying to decide if the "out_settings" is needed, but leaning towards leaving it out. Do you think it is useful? Especially when used from QGIS, I do not think these would ever be used, and in scripts one could pretty easily fetch this information from other parts of the code too, probably.

Any relevant default values set in `eis_toolkit` should be adjustable from the
QGIS interface. So the user should already know before running a function
there, what values he is using in the function. In this case I do not see the
need for `out_settings`. However, if defaults are used in code that are not
adjustable by the user, these should be somehow reported (probably not a good
practice). This is more of a general issue than anything related to
`transformations` module.

> I would like to have actual assertions in the tests, showing that the output is as intended. Now the tests only test exceptions.

Currently, very little is actually tested as there is no checking if the
outputs are even of the types that are expected. I would start by only adding
test cases for the `_core` functions where you check that the outputs are of
the right type and that they fulfill some criteria, even checking that the
array values are exactly the same as some expected values.
